server:
  servlet:
    context-path: /api

#springdoc:
#  paths-to-match:
#    - /api/**
#  packages-to-scan: com.pokerface.pokerface
#  default-consumes-media-type: application/json;charset=UTF-8
#  default-produces-media-type: application/json;charset=UTF-8
#  swagger-ui:
#    path: /swagger-ui.html            # Swagger UI 경로 => localhost:8000/demo-ui.html
#    tags-sorter: alpha            # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
#    operations-sorter: alpha      # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
#  api-docs:
#    path: /api-docs/json
#    groups:
#      enabled: true
#  cache:
#    disabled: true


spring:
  mvc:
    throw-exception-if-no-handler-found: true
    pathmatch:
      matching-strategy: ant_path_matcher
  #    pathmatch:
#      matching-strategy: ant_path_matcher
  config:
    import: openvidu.yml, mysql.yml, redis.yml, jwt.yml, mail.yml, oauth.yml

logging:
  level:
    root: info
    pokerface:
      pokerface: debug
    org.hibernate.sql: info
    org.hibernate.type.descriptor.sql: trace
    org.springframework.security.web.FilterChainProxy: DEBUG
---
spring:
  config:
    activate:
      on-profile: set1
server:
  port: 8081
  servlet:
    context-path: /api
---
spring:
  config:
    activate:
      on-profile: set2
server:
  port: 8082
  servlet:
    context-path: /api
