server:
  servlet:
    context-path: /api

# Swagger
springfox:
  documentation:
    swagger:
      use-model-v3: 'false'

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  config:
    import: openvidu.yml, mysql.yml, redis.yml, jwt.yml

logging:
  level:
    org.hibernate.sql: debug

---
spring:
  config:
    activate:
      on-profile: set1
server:
  port: 8081
  servlet:
    context-path: /api
---
spring:
  config:
    activate:
      on-profile: set2
server:
  port: 8082
  servlet:
    context-path: /api
