server:
  servlet:
    context-path: /api

# Swagger
springfox:
  documentation:
    swagger:
      use-model-v3: 'false'


spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        show_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://52.79.146.194:3306/pokerface?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234
  mvc:
    throw-exception-if-no-handler-found: true

logging:
  level:
    org.hibernate.sql: debug

---
spring:
  config:
    activate:
      on-profile: set1
server:
  port: 8081
  servlet:
    context-path: /api
---
spring:
  config:
    activate:
      on-profile: set2
server:
  port: 8082
  servlet:
    context-path: /api
