spa:
  default-file: /static/index.html

# Swagger
springfox:
  documentation:
    swagger:
      use-model-v3: 'false'


spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        show_sql: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://stg-yswa-kr-practice-db-master.mariadb.database.azure.com:3306/S09P12A603
    username: S09P12A603
    password: DkyeFRtWLR
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
      static-locations: classpath:/static/

logging:
  level:
    org.hibernate.sql: debug

---
spring:
  config:
    activate:
      on-profile: set1
server:
  port: 8081
---
spring:
  config:
    activate:
      on-profile: set2
server:
  port: 8082
