spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        show_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://52.79.146.194:3306/pokerface?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234